https://machinelearningmastery.com/singular-value-decomposition-for-machine-learning/#:~:text=The%20singular%20value%20decomposition%20%28SVD%29%20has

In [1]:
# Reconstruct SVD
from numpy import array
from numpy import diag
from numpy import dot
from scipy.linalg import svd

# define a matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
# create n x n Sigma matrix
Sigma = diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [3]:
s, Sigma

(array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]),
 array([[1.68481034e+01, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 1.06836951e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 3.33475287e-16]]))